import { Plus, Search, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import toast from 'react-hot-toast'

import { Modal } from '../components/Modal'
import { Pagination } from '../components/Pagination'
import { getApiError } from '../hooks/useApiError'
import { professionalService } from '../services/crud.service'
import type { Disponibilidade, Paginated, Profissional } from '../types'
import { formatDateTime, toTimeInput } from '../utils/format'

export function ProfissionaisPage() {
  const [result, setResult] = useState<Paginated<Profissional> | null>(null), [page, setPage] = useState(1), [query, setQuery] = useState(''), [item, setItem] = useState<Profissional | null>(null), [availability, setAvailability] = useState<Disponibilidade[] | null>(null)
  const load = useCallback(() => professionalService.list({ page, limit: 10, q: query }).then(setResult).catch((e) => toast.error(getApiError(e))), [page, query]); useEffect(() => { void load() }, [load])
  const save = async (form: HTMLFormElement) => { const data = Object.fromEntries(new FormData(form)); try { await professionalService.save({ ...data, id: item?.id, email: String(data.email || '') || null, especialidade: String(data.especialidade || '') || null }); toast.success('Profissional salvo.'); setItem(null); void load() } catch (e) { toast.error(getApiError(e)) } }
  const openAvailability = async (professional: Profissional) => { setItem(professional); try { setAvailability(await professionalService.availability(professional.id)) } catch (e) { toast.error(getApiError(e)) } }
  return <div className="space-y-6"><div className="flex justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-blue-600">Cadastros</p><h1 className="text-3xl font-bold">Profissionais</h1></div><button onClick={() => setItem({ id: '', nome: '', documento: '', email: '', telefone: '', especialidade: '', ativo: true })} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white"><Plus size={18} />Novo profissional</button></div><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="relative mb-5 max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={18} /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1) }} className="w-full rounded-xl border py-2.5 pl-10" placeholder="Buscar profissional" /></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Nome</th><th className="p-3">Especialidade</th><th className="p-3">Telefone</th><th className="p-3 text-right">Ações</th></tr></thead><tbody>{result?.data.map((p) => <tr key={p.id} className="border-b border-slate-100"><td className="p-3 font-semibold">{p.nome}</td><td className="p-3">{p.especialidade || '—'}</td><td className="p-3">{p.telefone}</td><td className="p-3 text-right"><button onClick={() => setItem(p)} className="mr-2 rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">Editar</button><button onClick={() => void openAvailability(p)} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold">Disponibilidade</button></td></tr>)}</tbody></table></div>{result && <Pagination result={result} onChange={setPage} />}</section>{item && !availability && <Modal title={item.id ? 'Editar profissional' : 'Novo profissional'} onClose={() => setItem(null)}><form onSubmit={(e) => { e.preventDefault(); void save(e.currentTarget) }} className="grid gap-4 md:grid-cols-2">{[['nome','Nome'],['documento','Documento'],['email','E-mail'],['telefone','Telefone'],['especialidade','Especialidade']].map(([name,label]) => <label key={name} className="text-sm font-semibold">{label}<input name={name} type={name === 'email' ? 'email' : 'text'} required={name !== 'email' && name !== 'especialidade'} defaultValue={item[name as keyof Profissional] as string ?? ''} className="mt-1 w-full rounded-lg border p-2" /></label>)}<div className="md:col-span-2 flex justify-end"><button className="rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white">Salvar</button></div></form></Modal>}{item && availability && <AvailabilityModal professional={item} values={availability} close={() => { setItem(null); setAvailability(null) }} refresh={async () => setAvailability(await professionalService.availability(item.id))} />}</div>
}
function AvailabilityModal({ professional, values, close, refresh }: { professional: Profissional; values: Disponibilidade[]; close: () => void; refresh: () => Promise<void> }) { const add = async (form: HTMLFormElement) => { try { const value = Object.fromEntries(new FormData(form)); await professionalService.addAvailability(professional.id, { ...value, horaInicio: `1970-01-01T${value.horaInicio}:00.000Z`, horaFim: `1970-01-01T${value.horaFim}:00.000Z` }); form.reset(); await refresh(); toast.success('Disponibilidade adicionada.') } catch (e) { toast.error(getApiError(e)) } }; return <Modal title={`Disponibilidade — ${professional.nome}`} onClose={close}><form onSubmit={(e) => { e.preventDefault(); void add(e.currentTarget) }} className="mb-5 grid gap-3 sm:grid-cols-3"><input name="data" type="date" required className="rounded-lg border p-2" /><input name="horaInicio" type="time" required className="rounded-lg border p-2" /><input name="horaFim" type="time" required className="rounded-lg border p-2" /><button className="rounded-lg bg-blue-600 px-3 py-2 font-semibold text-white sm:col-span-3">Adicionar horário</button></form><div className="space-y-2">{values.map((v) => <div key={v.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{formatDateTime(v.data)} · {toTimeInput(v.horaInicio)}–{toTimeInput(v.horaFim)}</span><button onClick={async () => { await professionalService.removeAvailability(professional.id, v.id); await refresh() }} className="text-rose-600"><Trash2 size={17} /></button></div>)}{!values.length && <p className="text-slate-500">Nenhum horário registrado.</p>}</div></Modal> }
